"""Regenerate AGENTS.md from SKILL.md. Run by install.sh so it cannot drift."""
import pathlib, sys, re
root = pathlib.Path(__file__).resolve().parent.parent
skill = (root / "SKILL.md").read_text(encoding="utf-8")
body = re.sub(r"^---\n.*?\n---\n", "", skill, count=1, flags=re.S).lstrip()
header = (
    "# llvideo — video understanding for coding agents\n\n"
    "Codex / OpenAI-agent entry point. Identical contract to SKILL.md, and generated\n"
    "from it — do not edit this file by hand, edit SKILL.md and re-run install.sh.\n\n"
    "Install: `pip install -e .` then `llvideo providers`.\n\n"
)
(root / "AGENTS.md").write_text(header + body, encoding="utf-8")
# The plugin bundle needs its own copy of SKILL.md. Copy it rather than
# maintaining a second file that silently drifts from the first.
plugin_skill = root / "skills" / "llvideo" / "SKILL.md"
plugin_skill.parent.mkdir(parents=True, exist_ok=True)
plugin_skill.write_text(skill, encoding="utf-8")

print(f"AGENTS.md regenerated from SKILL.md ({len(body)} chars)")
print(f"skills/llvideo/SKILL.md refreshed from SKILL.md")
