"""Regenerate AGENTS.md from SKILL.md. Run by install.sh so it cannot drift."""
import pathlib, sys, re
root = pathlib.Path(__file__).resolve().parent.parent
skill = (root / "SKILL.md").read_text(encoding="utf-8")
body = re.sub(r"^---\n.*?\n---\n", "", skill, count=1, flags=re.S).lstrip()
header = (
    "# llvideo — video understanding for coding agents\n\n"
    "Codex / OpenAI-agent entry point. Identical contract to SKILL.md, and generated\n"
    "from it — do not edit this file by hand, edit SKILL.md and re-run install.sh.\n\n"
    "Install: `pip install -e .` then `llvideo providers`.\n\n"
)
(root / "AGENTS.md").write_text(header + body, encoding="utf-8")
print(f"AGENTS.md regenerated from SKILL.md ({len(body)} chars)")
